### ISSUE TITLE
Make production ready jar

### ISSUE THREAD

**Issue by gabizou** [gabizou/ThaumicSponge#1]
Currently, there's something wrong with the shading of jars where the API is not being included in the fat jar so to speak. There's an issue (currently) with attempting to extend a mixin from SpongeCommon, specifically that the superclass can't be resolved (even though the superclass is the exact same structure).

I'll deal with this tomorrow when I get a chance to review the potential issue with @Mumfrey.

**Comment by liach** [comment]
Does [this](https://github.com/gabizou/ThaumicSponge/commit/33b491e3a7930ad2eff8d3dfdde6b160259942f7#commitcomment-15921051) work?

**Comment by gabizou** [comment]
No.

**Comment by Mumfrey** [comment]
Closed via 0b908ed91189bc5216b1f07150cbec982b1e476c
